Jdp210501 3
piotr-grosicki/project-jdp-2105-01 pull request #3
Opened 2021-06-01 12:08 UTC by RadoslawZerek

Creating an initial endpoint implementation in CartController and creating the necessary domain objects

2021-06-01 17:43 UTC, piotr-grosicki requested changes

2021-06-01 17:43 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    public Cart createEmptyCart(CartDto cartDto) {
controllery nie powinny zwracac encji
ta metoda powinna przyjac jako parametr id usera

2021-06-01 17:43 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    @PatchMapping("/{id}/getProductFromEmptyCart/")
po co to id skoro nie jest uzyte w metodzie?

2021-06-01 17:43 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    @PutMapping("cart/addProduct")
cart juz jest w sciezce glownej w tym controllerze

2021-06-01 17:43 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    public CartDto addProductToCart(CartDto cartDto) {
ta metoda powinna przyjac id carta i id produktu

2021-06-01 17:43 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    public void deleteProductFromCart(Long id) {
parametr metody bez zadnej adnotacji nie bedzie dzialal, metoda powinna przyjac id produktu i id carta

2021-06-01 17:43 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    public Cart createAnOrderBasedOnACart() {
controllery nie moga zwracac encji, brakuje parametrow metody

2021-06-01 17:43 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +public class Cart {
encja nie powinna powstac w tym zadaniu

2021-06-01 17:43 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    @PostMapping(value = "createEmptyCart", consumes = MediaType.APPLICATION_JSON_VALUE)
warto zdecydowac sie czy uzywamy slasha na poczatku request mappingu czy nie, aktualnie jest to dosc losowe

2021-06-02 07:07 UTC, piotr-grosicki requested changes

2021-06-02 07:07 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    public void createAnOrderBasedOnACart(@RequestBody CartDto cartDto) {
na logike ta metoda powinna przyjac cart id a zwrocic order dto

2021-06-02 07:07 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    @PatchMapping("getProductFromEmptyCart/")
slash na koncu

2021-06-02 07:07 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +public class Cart {
nadal, nie usunieta

2021-06-02 07:08 UTC, piotr-grosicki requested changes
plus trzeba domergowac maina do branchy zeby byla aktualna

2021-06-02 21:41 UTC, RadoslawZerek commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    public void createAnOrderBasedOnACart(@RequestBody CartDto cartDto) {
Utworzyć klasę OrderDto, zamienić void na public OrderDto, parametr na @RequestParam Long cartId i jako zwracane dać new OrderDto - dobrze rozumuję?

2021-06-03 08:31 UTC, piotr-grosicki approved these changes

2021-06-03 08:31 UTC, merged