Cart entity added
piotr-grosicki/project-jdp-2105-01 pull request #7
Opened 2021-06-03 09:31 UTC by RadoslawZerek

2021-06-03 20:39 UTC, piotr-grosicki requested changes

2021-06-03 20:39 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +public class Cart {
projekt sie nie buduje, spojrz na komentarz w PR od usera

2021-06-03 20:39 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    private User userId;
pole powinno sie nazywac user a nie userId

2021-06-03 20:39 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/CartTestSuite.java
> +public class CartTestSuite {
czemu ta klasa testowa zostala tutaj dodana?

2021-06-04 08:50 UTC, RadoslawZerek commented on src/test/java/com/kodilla/ecommercee/CartTestSuite.java
> +public class CartTestSuite {
A nie wiem skąd się to tutaj wzięło, ogarnę to dzisiaj

2021-06-04 12:11 UTC, piotr-grosicki requested changes
projekt sie nie buduje, w wydmuszkach nie ma id + konflikt w product dto

2021-06-06 14:17 UTC, closed without merging