JDP210501-11
piotr-grosicki/project-jdp-2105-01 pull request #8
Opened 2021-06-03 19:26 UTC by Plastus1991

2021-06-03 20:36 UTC, Plastus1991 commented
Zmieniłem nazwę tabeli na ORDER_USER - jutro zaktualizuje. Nie wiem dlaczego ale jak jest nazwa ORDER to błąd wyrzuca.
To jest chyba keyword z SQL jak się nie mylę może dlatego .

2021-06-03 20:42 UTC, piotr-grosicki requested changes
projekt sie nie buduje + konflikty w userDto

2021-06-03 20:42 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/Order.java
> +    private User user;
w repozytorium NIGDY nie trzymamy zakomentowanego kodu. w tym zadaniu powinny powstac wydmuszki encji do ktorych sie odwolujesz (takie posiadajace tylko id). wydmuszki powinny zostac zamienione na prawdziwe implementacje w odpowiednich zadaniach

2021-06-07 06:02 UTC, piotr-grosicki approved these changes

2021-06-07 06:02 UTC, piotr-grosicki requested changes
konflikty

2021-06-07 12:28 UTC, merged